---
name: Build and Release
on:
  - push
env:
  SNYK_VERSION: "1.1276.0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: snyk/cli
          ref: refs/tags/v${{ env.SNYK_VERSION }}
          fetch-depth: 0  # some of the unit tests require repository history
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: apply patch for unexpected-error test expects non-colored output from https://github.com/snyk/cli/pull/4813
        run: curl --fail -Ls "https://github.com/candrews/snyk-cli/commit/558514ea87baca646d1161748b00e027ef72f321.patch" | git apply
      - name: apply patch adding the client-sbom creation feature
        run: curl --fail -Ls "https://github.com/candrews/snyk-cli/commit/a121de8e0082c0e7c906bcf4f3e970df77c6b800.patch" | git apply
      - name: Install dependencies
        run: npm ci
      - name: make pre-build
        run: make pre-build
      - name: build
        run: npm run build:prod
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"  # snyk should upgrade to a newer version of webpack that doesn't require this workaround: https://github.com/snyk/cli/pull/4147
      - name: Set Snyk token
        run: node ./bin/snyk config set "api=${TEST_SNYK_TOKEN}" # many tests require the token to be in the config. At least one ("succeed testing with correct exit code - and analytics added" in test/jest/unit/snyk-code/snyk-code-test.spec.ts) requires it to be set to "123456789"
        env:
          TEST_SNYK_TOKEN: "123456789"
      - name: run unit tests
        run: npm run test:unit
        env:
          FORCE_COLOR: "1"  # Some tests check for ANSI color codes. chalk doesn't enable color by default for the terminal settings used by GitHub Actions, so color must be forced.
      - name: prepack
        run: npx ts-node ./release-scripts/prune-dependencies-in-packagejson.ts
      - name: set package name to @candrewsintegralblue/snyk
        run: npm pkg set name="@candrewsintegralblue/snyk"
      - name: set package version
        run: npm version "$SNYK_VERSION" --no-git-tag-version --workspaces --include-workspace-root
      - name: package
        run: npm pack
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: "*.tgz"
          if-no-files-found: error
      - name: publish dry run
        run: npm publish --access public --dry-run *.tgz
  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.ref_name == 'master'
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: 'https://registry.npmjs.org'
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: package
      - name: publish
        run: npm publish --access public *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
